### PR TITLE
fixed GetTariffInfoForEmployeeDtoMapper null pointer exception.

### LINKED ISSUE #7199: GET /admin/ubs-employee/getAll-employees - return 400 status instead of 200.
When the user is logged in like a UBS Admin and sends the request to the endpoint:  /admin/ubs-employee/getAll-employees, he gets 400 response status instead of 200.

### PR DESCRIPTION
**Pull request by ryhaldenys**
# GreenCity PR
## Summary Of Changes :fire:
- fixed throwing of null pointer exception in the GetTariffInfoForEmployeeDtoMapper.

# PR Checklist Forms

_(to be filled out by PR submitter)_
- [x] Code is up-to-date with the `dev` branch.
- [x] You've successfully built and run the tests locally.
- [x] There are new or updated unit tests validating the change.
- [x] JIRA/ Github Issue number & title in PR title (ISSUE-XXXX: Ticket title)
- [x] This template filled (above this section).
- [ ] Sonar's report does not contain bugs, vulnerabilities, security issues, code smells or duplication
- [x] `NEED_REVIEW` and `READY_FOR_REVIEW` labels are added.
- [x] All files reviewed before sending to reviewers

### CODE REVIEW

**Review by KizerovDmitriy — APPROVED** [review]

**Review by staaankey — APPROVED** [review]

File: service/src/main/java/greencity/mapping/tariff/GetTariffInfoForEmployeeDtoMapper.java [hunk 1]
```diff
@@ -21,23 +20,23 @@ protected GetTariffInfoForEmployeeDto convert(TariffsInfo source) {
                 .nameUk(tariffLocation.getLocation().getRegion().getUkrName())
                 .nameEn(tariffLocation.getLocation().getRegion().getEnName())
                 .build())
-            .toList().getFirst();
+            .findFirst().orElse(null);
```
Comment (staaankey) [inline service/src/main/java/greencity/mapping/tariff/GetTariffInfoForEmployeeDtoMapper.java]: Here`s probably better to use orElseThrow() instead of keep storing null in the application imo

**Review by HelenSotnik — APPROVED** [review]

**Review by HelenSotnik — APPROVED** [review]

File: service/src/main/java/greencity/mapping/tariff/GetTariffInfoForEmployeeDtoMapper.java (hunk 1 above)
Comment (ryhaldenys) [reply service/src/main/java/greencity/mapping/tariff/GetTariffInfoForEmployeeDtoMapper.java]: If I throw the exception here the method for getting all employees will not work because 
 the employee may not have info about the region.
