### PR TITLE
Fix/1751 manager login hang on invalid password

### LINKED ISSUE #1751: Fix manager login hang on invalid password
When attempting to log in as a manager with an incorrect password, the bot throws an unhandled exception instead of showing an error message. As a result, the chat freezes. The flow should catch the error and return a proper user-facing message.

### PR DESCRIPTION
**Pull request by AnastasiaRakuta**
# GreenCityUBS PR
## Issue Link :clipboard:
[#1751](https://github.com/ita-social-projects/GreenCityUBS/issues/1751)
## Changed

- Wrapped manager login flow in try-catch to handle BadRequestException and generic exceptions
- Returned user-friendly message for invalid password
- Added unit tests for new logic

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved error messages during login to distinguish between incorrect password and other errors.
  * Users now receive a specific message if their password is incorrect, and a generic message for other login issues.

* **Tests**
  * Enhanced test coverage for login error handling, including scenarios for incorrect passwords and other exceptions.

### CODE REVIEW

File: service/src/main/java/greencity/constant/TelegramBotConstants.java [hunk 1]
```diff
@@ -178,4 +178,6 @@ public class TelegramBotConstants {
 
     public static final String PHOTO_CONTENT =
         "Фото контент";
+
+    public static final String LOGIN_FAILED = "Неправильний пароль. Спробуйте ще раз";
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/constant/TelegramBotConstants.java]: Could you consider returning a more generic message instead of telling the incorrect password? This improves security by preventing attackers from confirming that they use a valid username.

Comment (RomaMocherniuk) [inline service/src/main/java/greencity/constant/TelegramBotConstants.java]: Should it be localized?

Comment (AnastasiaRakuta) [reply service/src/main/java/greencity/constant/TelegramBotConstants.java]: Yes, localization is scheduled for another pull request

Comment (AnastasiaRakuta) [reply service/src/main/java/greencity/constant/TelegramBotConstants.java]: Thanks, now the message is more generic

**Review by SaenkoVova — APPROVED** [review]

**Review by antonpampukha — APPROVED** [review]

**Review by olehio-p — APPROVED** [review]
