### PR TITLE
[UBS Address] Fixed edit district

### LINKED ISSUE #6154: [UBS Address] District value is not visible when editing an address in EN mode
**Environment:** Windows 10 Google Chrome 113.0.5672.93
**Reproducible:** always
**Build found:** 10.08.2023

**Preconditions**
1.  The user should be logged in https://www.greencity.social/#/ubs as a user
2. User has at least 1 address (for example like on the screenshot)
3. There is 'EN' mode

**Steps to reproduce**
1. Go to UBS main page
2. Click on 'Order' btn
3. Go to the second step of the order
4. Click on the 'Edit address icon'

**Actual result**
The user doesn't see the district value due to using different services for handling address and district information, leading to inconsistency in the English language spelling.image

**Expected result**
The user should see the district value when editing the address
image

### PR DESCRIPTION
**Pull request by ospodaryk**
# GreenCityUBS PR
[[UBS Address] District value is not visible when editing an address in EN mode #6154
](https://github.com/ita-social-projects/GreenCity/issues/6154)

## Summary Of Changes :fire:
Added setting districts from dto which comes

## Added
Added setting districts from dto which comes

# PR Checklist Forms

_(to be filled out by PR submitter)_
- [ ] Code is up-to-date with the `dev` branch.
- [x] You've successfully built and run the tests locally.
- [x] There are new or updated unit tests validating the change.
- [x] JIRA/ Github Issue number & title in PR title (ISSUE-XXXX: Ticket title)
- [x] This template filled (above this section).
- [x] Sonar's report does not contain bugs, vulnerabilities, security issues, code smells ar duplication
- [x] `NEED_REVIEW` and `READY_FOR_REVIEW` labels are added.
- [x] All files reviewed before sending to reviewers

### CODE REVIEW

File: service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java [hunk 1]
```diff
@@ -582,6 +582,10 @@ public OrderWithAddressesResponseDto saveCurrentAddressForOrder(CreateAddressReq
         address.setUser(currentUser);
         address.setActual(addresses.isEmpty());
         address.setAddressStatus(AddressStatus.NEW);
+
+        address.setDistrict(addressRequestDto.getDistrict());
+        address.setDistrictEn(addressRequestDto.getDistrictEn());
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java:587]: please add tests for the new functionality

Comment (ospodaryk) [reply service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java:587]: added

File: service/src/test/java/greencity/service/ubs/UBSClientServiceImplTest.java [hunk 2]
```diff
@@ -118,91 +118,8 @@
...
 import java.util.stream.Collectors;
 
-import static greencity.ModelUtils.KYIV_REGION_EN;
-import static greencity.ModelUtils.KYIV_REGION_UA;
-import static greencity.ModelUtils.TEST_BAG_FOR_USER_DTO;
-import static greencity.ModelUtils.TEST_BAG_LIST;
-import static greencity.ModelUtils.TEST_EMAIL;
-import static greencity.ModelUtils.TEST_ORDER_ADDRESS_DTO_REQUEST;
-import static greencity.ModelUtils.TEST_PAYMENT_LIST;
+import static greencity.ModelUtils.*;
```
Comment (RomaMocherniuk) [inline service/src/test/java/greencity/service/ubs/UBSClientServiceImplTest.java]: please do not use `*`

**Review by sergoliarnik — APPROVED** [review]

**Review by 2or5 — APPROVED** [review]

**Review by ABbondar — APPROVED** [review]
