### PR TITLE
#5660 bug ubs tg notification title lang

### LINKED ISSUE #5660: [UBS notifications] Telegram notification title is always in Ukrainian language
Environment: Windows 10 Pro, Opera 97.0.4719.63
Reproducible: always

**Preconditions**
User is authorized

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/#/ubs-user/orders
2. Click on 'New order'
3. Confirm the order and pay
4. Get the notification on the Telegram bot

**Actual result**
Notification title is always in Ukrainian language

**Expected result**
Title and message should be the same language

### PR DESCRIPTION
**Pull request by Maksym-Lenets**
## Summary Of Issue :
Notification title is always in Ukrainian language

**Issue Link**
https://github.com/ita-social-projects/GreenCity/issues/5660

## Summary Of Changes 
 Added condition that changes the language of the message title according to user profile settings

## CHECK LIST
- [x] Code is up-to-date with the `dev` branch.
- [x] You've successfully built and run the tests locally.
- [x] There are new or updated unit tests validating the change.
- [x] JIRA/ Github Issue number & title in PR title (ISSUE-: Ticket title)
- [x] This template filled (above this section).
- [x] Sonar's report does not contain bugs, vulnerabilities, security issues, code smells ar duplication
- [x] All files reviewed before sending to reviewers

### CODE REVIEW

**Review by ABbondar — APPROVED** [review]

**Review by BranetE — APPROVED** [review]

**Review by juseti — APPROVED** [review]

**Review by sergoliarnik — APPROVED** [review]

**Review by LiliaMokhnatska — APPROVED** [review]

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 1]
```diff
@@ -503,8 +503,9 @@ public static NotificationDto createNotificationDto(UserNotification notificatio
 
         StringSubstitutor sub = new StringSubstitutor(valuesMap);
         String resultBody = sub.replace(String.format(templateBody, monthsOfAccountInactivity));
+        String title = language.equals("ua") ? template.getTitle() : template.getTitleEng();
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java:506]: please add test

**Review by RomaMocherniuk — APPROVED** [review]
