### PR TITLE
#4983 fix test/tests for order for user service

### LINKED ISSUE #4983: [UBS] - Tests should be improved for getAllOrders method in OrdersForUserServiceImpl
Method getAllOrders in OrdersForUserServiceImpl should be fully covered

### PR DESCRIPTION
**Pull request by MaksymGolik**
* Fixed the implementation of getAllOrders in OrdersForUserServiceImpl method (not all cases worked correctly before)

* Removed methods from the OrdersForUserRepository that are not working (the problem is in using native query sorting and pageable sorting) and are not being used

* Added parametrized tests for OrdersForUserServiceImpl

### CODE REVIEW

File: service/src/main/java/greencity/service/ubs/OrdersForUserServiceImpl.java [hunk 1]
```diff
@@ -6,18 +6,18 @@
...
 import org.springframework.data.domain.Sort;
 import org.springframework.stereotype.Service;
 
-import java.util.ArrayList;
 import java.util.List;
 import java.util.stream.Collectors;
 
 @Service
-@Data
+@AllArgsConstructor
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/ubs/OrdersForUserServiceImpl.java:19]: please make all fields `private`

File: service/src/test/java/greencity/service/ubs/OrdersForUserServiceImplTest.java [hunk 2]
```diff
@@ -3,41 +3,47 @@
...
+        ordersForUserService.getAllOrders(PageRequest.of(1, 1), 1L, sortingOrder, column);
 
         verify(ordersForUserRepository).getAllOrdersByUserId(PageRequest.of(10, 10, sort), 1L);
     }
+
+    private static Stream<Arguments> provideSortingOrdersAndColumnsForGetAllOrders() {
+        return Stream.of(
+            Arguments.of(SortingOrder.ASC, "payment_amount"),
+            Arguments.of(SortingOrder.DESC, "payment_amount"),
+            Arguments.of(SortingOrder.ASC, "order_status"));
```
Comment (RomaMocherniuk) [inline service/src/test/java/greencity/service/ubs/OrdersForUserServiceImplTest.java]: please add` Arguments.of(SortingOrder.ASC, "order_status")`

**Comment by RomaMocherniuk** [comment]
Please remove unused imports
image

**Review by JJJazl — APPROVED** [review]

**Review by Markiro1 — APPROVED** [review]

**Review by ABbondar — APPROVED** [review]

**Review by juseti — APPROVED** [review]
