### PR TITLE
#5796 [UBS] Throw NotFoundException when employee doesn't have a saved columns width

### LINKED ISSUE #5796: [Admin table] Affected functionality for new admin
**Environment:** Windows 10 
**Reproducible:** always
**Build found:** 15/05/2023

**Preconditions**
The user is logged in as an administrator
Go to (https://www.testgreencity.ga/GreenCityClient/#/ubs-admin)

**Steps to reproduce**
1. Open the big order table
2. Try to resize the column widths
3. Check the console the error message

**Actual result**
The new admin can't resize the column widths
image

**Expected result**
The new admin can resize the column width and there is no error message

### PR DESCRIPTION
**Pull request by Maksym-Lenets**
**Issue Link**
https://github.com/ita-social-projects/GreenCity/issues/5796

**Endpoint to test**
[admin-ubs-controller]: GET: ubs/management/orderTableColumnsWidth

## Summary Of Changes :
1) Added a constructor that will create TableColumnWidthForEmployee with the same width for all columns.

## CHECK LIST
- [x] Code is up-to-date with the `dev` branch.
- [x] You've successfully built and run the tests locally.
- [x] There are new or updated unit tests validating the change.
- [x] JIRA/ Github Issue number & title in PR title (ISSUE-: Ticket title)
- [x] This template filled (above this section).
- [x] Sonar's report does not contain bugs, vulnerabilities, security issues, code smells or duplication
- [x] All files reviewed before sending to reviewers

### CODE REVIEW

File: dao/src/test/java/greencity/entity/table/TableColumnWidthForEmployeeTest.java [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+
+import static org.junit.jupiter.api.Assertions.assertEquals;
+
+class TableColumnWidthForEmployeeTest {
+    @Test
+    void TableColumnWidthForEmployeeWithDefaultWidthTest() {
+        Employee employee = Employee.builder().build();
+        TableColumnWidthForEmployee tableColumnWidth = new TableColumnWidthForEmployee(employee);
+        int defaultWidth = 120;
+        assertEquals(defaultWidth, tableColumnWidth.getAddress());
```
Comment (RomaMocherniuk) [inline dao/src/test/java/greencity/entity/table/TableColumnWidthForEmployeeTest.java:15]: please add `assertEquals` for `employee` too

File: service/src/test/java/greencity/ModelUtils.java [hunk 2]
```diff
@@ -4502,6 +4502,46 @@ public static TableColumnWidthForEmployee getTestTableColumnWidth() {
             .build();
     }
 
+    public static TableColumnWidthForEmployee getTestTableColumnWidthForEmployeeWithDefaultValues() {
+        return TableColumnWidthForEmployee.builder()
+            .employee(getEmployee())
+            .address(120)
```
Comment (RomaMocherniuk) [inline service/src/test/java/greencity/ModelUtils.java]: do we need to set the width for every column? It is the default value
You can just call constrictor `TableColumnWidthForEmployee(getEmployee())`

File: dao/src/main/java/greencity/entity/table/TableColumnWidthForEmployee.java [hunk 3]
```diff
@@ -11,80 +14,89 @@
 @AllArgsConstructor
 @NoArgsConstructor
 @Builder
-@EqualsAndHashCode
-@ToString
 public class TableColumnWidthForEmployee {
+    private static final Integer TABLE_DEFAULT_COLUMN_WIDTH = 120;
```
Comment (RomaMocherniuk) [inline dao/src/main/java/greencity/entity/table/TableColumnWidthForEmployee.java]: I think the constant name could be changed to `DEFAULT_WIDTH`
We have already known from the class name that it is for `Table Column Width`

**Review by RomaMocherniuk — APPROVED** [review]

**Review by sergoliarnik — APPROVED** [review]

**Review by juseti — APPROVED** [review]

**Review by ABbondar — APPROVED** [review]
