### PR TITLE
Remove usage of external territorial communities API

### LINKED ISSUE #8596: [UBS Admin. Address] New addresses can't be created for some cities.
**Environment:** Windows 10, Google Chrome Version 130.0.6723.117 (Official Build) (64-bit)

**Preconditions**
User is logged in.

**Steps to reproduce**
https://github.com/user-attachments/assets/b28ea36d-f2e7-4164-8a07-52f5a52cfb60

**Actual result**
The new address hasn't been created.
The error message in response:
"ModelMapper mapping errors:\n\n1) Converter Converter<class greencity.entity.user.ubs.Address, class greencity.dto.address.AddressDto> failed to convert greencity.entity.user.ubs.Address to greencity.dto.address.AddressDto.\n\n1 error"

**Expected result**
The new address has been created.

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

### LINKED ISSUE #8760: [API][UBS Address] Remove usage of external territorial communities API (directory.org.ua)
**Description of ToDo:**
Remove all logic, configurations, and dependencies related to the external API of the territorial communities reference directory (https://directory.org.ua/api/katottg).
Replace all usages of this API with new logic that does not rely on it.

**Reason for Change:**
The external territorial communities API has become paid.
To avoid additional costs and dependency on a third-party provider, have decided to fully switch to using only the Google Maps API for geolocation and address-related data.

### PR DESCRIPTION
**Pull request by BohdanLys**
# GreenCityUBS PR
## Issue Link 📋
<a href="https://github.com/ita-social-projects/GreenCity/issues/8760">#8760</a>
<a href="https://github.com/ita-social-projects/GreenCity/issues/8596">#8596</a>

## Changed

- Deleted usages of Location API in code;
- Implemented new logic for retrieving districts for city;

## Summary by CodeRabbit

* **Refactor**
  * Updated district and city data retrieval to use direct database queries instead of external API calls, improving performance and reliability.
  * Streamlined internal logic for handling districts and cities across address-related features.
  * Introduced a new method to retrieve city IDs by exact name matching in Ukrainian or English for more efficient data access.

* **Bug Fixes**
  * Improved filtering of Kyiv districts to exclude both "Kyiv City" and "Kyiv" from results.

### CODE REVIEW

File: service/src/main/java/greencity/service/ubs/UBSManagementServiceImpl.java [hunk 1]
```diff
@@ -66,27 +66,7 @@
...
-import greencity.repository.OrderStatusTranslationRepository;
-import greencity.repository.PaymentRepository;
-import greencity.repository.PositionRepository;
-import greencity.repository.ReceivingStationRepository;
-import greencity.repository.ServiceRepository;
-import greencity.repository.TariffsInfoRepository;
-import greencity.repository.UserNotificationRepository;
-import greencity.repository.UserRepository;
-import greencity.service.locations.LocationApiService;
+import greencity.repository.*;
```
Comment (oleksandr-ilnytskyi) [inline service/src/main/java/greencity/service/ubs/UBSManagementServiceImpl.java]: Import only those that are actually used

Comment (BohdanLys) [reply service/src/main/java/greencity/service/ubs/UBSManagementServiceImpl.java]: Will change it

**Review by oleksandr-ilnytskyi — APPROVED** [review]

**Review by antonpampukha — APPROVED** [review]

**Review by RomikSm — APPROVED** [review]
