### PR TITLE
Bugfix #8891 - Added proper validation for tariffs

### LINKED ISSUE #8891: [UBS API] 500 Internal Server Error with duplicate tariffId in request
**Environment:** OS: Windows 10, Postman v11.40.2
**Reproducible:** always
**Build found:** 07-23-2025

**Preconditions**
1. Authorize as Admin
2. Set a request POST /admin/ubs-employee/save-employee

**Steps to reproduce**
1. Open Postman.
2. Create a POST request to /admin/ubs-employee/save-employee.
3. In the body of the request, pass:
 "tariffs": [
  { "tariffId": 1, "hasChat": true },
  { "tariffId": 1, "hasChat": false }
]
4. Send request

**Actual result**
The server returns 500 Internal Server Error

**Expected result**
- The server returns 400 Bad Request with an explanation that the tariffId must be unique within a single request or:
- The last object overwrites the previous one (if such logic is supported).

### PR DESCRIPTION
**Pull request by markotymofeiuk**
# GreenCityUBS PR
## Issue Link :clipboard:
[#8891](https://github.com/ita-social-projects/GreenCity/issues/8891)

## Summary Of Changes :fire:
Introduced `ValidTariffs` constraint and `TariffsValidator` to properly handle tariffs in `EmployeeWithTariffsDto`.

## Added
* `ValidTariffs` constraint
* `TariffsValidator`
* `TariffsValidatorTest`

## Changed
* Applied `ValidTariffs` validation to `EmployeeWithTariffsDto`.

## Summary by CodeRabbit

* **New Features**
  * Introduced custom validation for tariff lists, ensuring each tariff entry is valid and all tariff IDs are unique.
  * Added multiple new error messages related to tariff validation.

* **Bug Fixes**
  * Improved validation logic for employee tariff data, replacing previous checks with more comprehensive validation.

* **Tests**
  * Added unit tests to verify the new tariff validation functionality.

* **Documentation**
  * Updated API documentation to reorder response codes for improved clarity.

### CODE REVIEW

**Review by antonpampukha — APPROVED** [review]

**Review by RostyslavZadyraichuk — APPROVED** [review]

**Review by BohdanLys — APPROVED** [review]

File: service-api/src/main/java/greencity/validator/TariffsValidator.java [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+import java.util.List;
+import java.util.Set;
+
+public class TariffsValidator implements ConstraintValidator<ValidTariffs, List<TariffWithChatAccess>> {
+    @Override
+    public boolean isValid(List<TariffWithChatAccess> tariffs, ConstraintValidatorContext context) {
+        context.disableDefaultConstraintViolation();
+
+        if (tariffs == null) {
+            context.buildConstraintViolationWithTemplate("tariffs cannot be null")
```
Comment (RomaMocherniuk) [inline service-api/src/main/java/greencity/validator/TariffsValidator.java]: Could you please move to the constants all the strings you use

File: service-api/src/main/java/greencity/validator/TariffsValidator.java [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+        for (TariffWithChatAccess tariff : tariffs) {
+            if (tariff == null) {
+                context.buildConstraintViolationWithTemplate("tariff cannot be null")
+                    .addConstraintViolation();
+                return false;
+            }
+
+            Long tariffId = tariff.getTariffId();
+
+            if (tariffId == null) {
```
Comment (RomaMocherniuk) [inline service-api/src/main/java/greencity/validator/TariffsValidator.java:44]: Should we check as well if the tariffId is greater than 0?

File: service-api/src/test/java/greencity/validator/TariffsValidatorTest.java [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+class TariffsValidatorTest {
+    @Mock
+    private ConstraintValidatorContext.ConstraintViolationBuilder builder;
+    @Mock
+    private ConstraintValidatorContext context;
+    @InjectMocks
+    private TariffsValidator validator;
+
+    @Test
+    void isValid() {
```
Comment (RomaMocherniuk) [inline service-api/src/test/java/greencity/validator/TariffsValidatorTest.java]: Please create a separate test for every case

Comment (RomaMocherniuk) [reply service-api/src/test/java/greencity/validator/TariffsValidatorTest.java]: or use Parametrize test

**Review by RomaMocherniuk — APPROVED** [review]

File: service-api/src/main/java/greencity/validator/TariffsValidator.java (hunk 2 above)
Comment (markotymofeiuk) [reply service-api/src/main/java/greencity/validator/TariffsValidator.java:44]: Initially, I considered adding this check but skipped it since the repository lookup already covers it. However, on second thought, I decided to include it in `TariffsValidator` to make the validation more comprehensive. Thanks for pointing it out!
