### PR TITLE
#5685 [UBS] Blank amount to pay in the scheduled notification for unpaid orders

### LINKED ISSUE #5685: [UBS] Blank "unpaid amount" in scheduled notification
**Steps to reproduce**
1. Create new order
2. Do not pay for this order
3. Receive notification

**Actual result**
img

**Expected result**
${amountToPay} should be filled with the unpaid amount

### PR DESCRIPTION
**Pull request by Maksym-Lenets**
## Summary Of Issue :
${amountToPay} is not filled with an unpaid amount

**Issue Link**
https://github.com/ita-social-projects/GreenCity/issues/5685

## Summary Of Changes :
1) fixed notifyUnpaidOrders method
2) refactored notifyUnpaidOrder and notifyHalfPaidPackage, shared logic extracted in getAmountToPay and initialiseNotificationParametersForUnpaidOrder methods
3) updated changelog with notifications that contain the payButton link
4) refactored old tests

## CHECK LIST
- [x] Code is up-to-date with the `dev` branch.
- [x] You've successfully built and run the tests locally.
- [x] There are new or updated unit tests validating the change.
- [x] JIRA/ Github Issue number & title in PR title (ISSUE-: Ticket title)
- [x] This template filled (above this section).
- [x] Sonar's report does not contain bugs, vulnerabilities, security issues, code smells or duplication
- [x] All files reviewed before sending to reviewers

### CODE REVIEW

**Review by sergoliarnik — APPROVED** [review]

**Review by MarkAndzh — APPROVED** [review]

**Review by ABbondar — APPROVED** [review]

**Review by LiliaMokhnatska — APPROVED** [review]

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 1]
```diff
@@ -99,18 +102,38 @@ private boolean checkIfUnpaidOrderNeedsNewNotification(Order order, Optional<Use
...
-        notificationParameter.setKey(ORDER_NUMBER_KEY);
-        notificationParameter.setValue(order.getId().toString());
-        notificationParameter.setUserNotification(notification);
-        NotificationParameter createdParameter = notificationParameterRepository.save(notificationParameter);
-        notification.setParameters(Collections.singleton(createdParameter));
-        return notification;
+    private Set<NotificationParameter> initialiseNotificationParametersForUnpaidOrder(Order order, Long amountToPay) {
+        Set<NotificationParameter> parameters = new HashSet<>();
+
+        parameters.add(NotificationParameter.builder().key(AMOUNT_TO_PAY_KEY)
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java]: please use better formating

```
parameters.add(
    NotificationParameter.builder()
        .key(AMOUNT_TO_PAY_KEY)
        .value(String.format("%.2f", (double) amountToPay))
    .build()
);

```

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 2]
```diff
@@ -99,18 +102,38 @@ private boolean checkIfUnpaidOrderNeedsNewNotification(Order order, Optional<Use
...
+            .value(String.format("%.2f", (double) amountToPay)).build());
+
+        parameters.add(NotificationParameter.builder()
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java:114]: same here

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 3]
```diff
@@ -99,18 +102,38 @@ private boolean checkIfUnpaidOrderNeedsNewNotification(Order order, Optional<Use
...
+            .build());
+
+        final String testGreenCity = "https://greencity-ubs.testgreencity.ga/ubs/details-for-existing-order/"
+            + order.getId();
+        final String pickUpCity = "https://greencity-ubs.pick-up.city/ubs/details-for-existing-order/"
+            + order.getId();
+
+        String hostName = inetAddressProvider.getInetAddressHostName();
+
+        if ("www.testgreencity.ga".equals(hostName)) {
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java:123]: can we store this data in the configs and load different data depending on the environment?

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 4]
```diff
@@ -99,18 +102,38 @@ private boolean checkIfUnpaidOrderNeedsNewNotification(Order order, Optional<Use
...
+                .value(testGreenCity)
+                .build());
+        }
+
+        if ("www.pick-up.city".equals(hostName)) {
+            parameters.add(NotificationParameter.builder()
+                .key("payButton")
+                .value(pickUpCity)
+                .build());
+        }
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java]: can we store this data in the configs and load different data depending on the environment?

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 5]
```diff
@@ -279,6 +223,46 @@ public void notifyUnpaidOrder(Order order) {
...
+        Long bonuses = order.getPointsToUse() == null ? 0L : order.getPointsToUse().longValue();
+        Long certificates = order.getCertificates() == null ? 0L
+            : order.getCertificates().stream()
+                .map(Certificate::getPoints)
+                .reduce(0, Integer::sum)
+                .longValue();
+
+        Long paidAmount = order.getPayment() == null ? 0L
+            : order.getPayment().stream()
+                .filter(payment -> payment.getPaymentStatus().equals(PaymentStatus.PAID))
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java]: You can use =`=` with enums
`payment.getPaymentStatus() == PaymentStatus.PAID`

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 6]
```diff
@@ -279,6 +223,46 @@ public void notifyUnpaidOrder(Order order) {
...
+                .map(payment -> payment.getAmount() / 100)
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java]: please do not use [magic numbers](https://www.javatpoint.com/magic-number-in-java#:~:text=If%20the%20single%20digit%20is,325%20is%20a%20magic%20number.)

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 7]
```diff
@@ -279,6 +223,46 @@ public void notifyUnpaidOrder(Order order) {
         }
     }
 
+    private Long getAmountToPay(Order order) {
+        Long bonuses = order.getPointsToUse() == null ? 0L : order.getPointsToUse().longValue();
+        Long certificates = order.getCertificates() == null ? 0L
+            : order.getCertificates().stream()
+                .map(Certificate::getPoints)
+                .reduce(0, Integer::sum)
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java:219]: can we use` Long::sum `here?

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 8]
```diff
@@ -279,6 +223,46 @@ public void notifyUnpaidOrder(Order order) {
...
+                .filter(payment -> payment.getPaymentStatus().equals(PaymentStatus.PAID))
+                .map(payment -> payment.getAmount() / 100)
+                .reduce(0L, Long::sum);
+
+        long ubsCourierSum = order.getUbsCourierSum() == null ? 0L : order.getUbsCourierSum();
+        long writeStationSum = order.getWriteOffStationSum() == null ? 0L : order.getWriteOffStationSum();
+
+        List<Bag> bags = bagRepository.findBagsByOrderId(order.getId());
+        Map<Integer, Integer> bagsAmount;
+        if (!order.getExportedQuantity().isEmpty()) {
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java]: Please use [CollectionUtils.isNotEmpty()](https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/CollectionUtils.html)

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 9]
```diff
@@ -279,6 +223,46 @@ public void notifyUnpaidOrder(Order order) {
...
+
+        long totalPrice = 0L;
+        for (Map.Entry<Integer, Integer> entry : bagsAmount.entrySet()) {
+            totalPrice += entry.getValue().longValue() * bags
+                .stream()
+                .filter(b -> b.getId().equals(entry.getKey()))
+                .findFirst()
+                .orElseThrow(() -> new NotFoundException(BAG_NOT_FOUND + entry.getKey()))
+                .getFullPrice();
+        }
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java]: Can we use stream here?

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java (hunk 7 above)
Comment (Maksym-Lenets) [reply service/src/main/java/greencity/service/notification/NotificationServiceImpl.java:219]: No, because getPoints return Integer and map return Stream Integer

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 10]
```diff
@@ -99,18 +103,27 @@ private boolean checkIfUnpaidOrderNeedsNewNotification(Order order, Optional<Use
...
+            .build());
+
+        parameters.add(NotificationParameter.builder()
+            .key(ORDER_NUMBER_KEY)
+            .value(order.getId().toString())
+            .build());
+
+        String orderUrl = environment.getProperty("greencity.ubs.unpaid-order-url") + order.getId();
+        parameters.add(NotificationParameter.builder()
+            .key("payButton")
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java]: please move this string to the constant

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 11]
```diff
@@ -99,18 +103,27 @@ private boolean checkIfUnpaidOrderNeedsNewNotification(Order order, Optional<Use
...
+            .key(AMOUNT_TO_PAY_KEY)
+            .value(String.format("%.2f", amountToPay))
+            .build());
+
+        parameters.add(NotificationParameter.builder()
+            .key(ORDER_NUMBER_KEY)
+            .value(order.getId().toString())
+            .build());
+
+        String orderUrl = environment.getProperty("greencity.ubs.unpaid-order-url") + order.getId();
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java]: please move `greencity.ubs.unpaid-order-url` to the constant

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 12]
```diff
@@ -279,6 +213,46 @@ public void notifyUnpaidOrder(Order order) {
...
+            : order.getCertificates().stream()
+                .map(Certificate::getPoints)
+                .reduce(0, Integer::sum)
+                .longValue();
+
+        double paidAmount = order.getPayment() == null ? 0d
+            : order.getPayment().stream()
+                .filter(payment -> payment.getPaymentStatus() == PaymentStatus.PAID)
+                .map(Payment::getAmount)
+                .reduce(0L, Long::sum) / 100.0;
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java]: please do not use magic numbers

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 13]
```diff
@@ -99,18 +105,27 @@ private boolean checkIfUnpaidOrderNeedsNewNotification(Order order, Optional<Use
...
+            .key(AMOUNT_TO_PAY_KEY)
+            .value(String.format("%.2f", amountToPay))
+            .build());
+
+        parameters.add(NotificationParameter.builder()
+            .key(ORDER_NUMBER_KEY)
+            .value(order.getId().toString())
+            .build());
+
+        String orderUrl = environment.getProperty(ORDER_URL_PROPERTY) + order.getId();
```
Comment (RomaMocherniuk) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java]: We can do it `environment.getProperty(ORDER_URL_PROPERTY)` once on startup and store to the variable

File: service/src/main/java/greencity/service/notification/NotificationServiceImpl.java [hunk 14]
```diff
@@ -51,25 +53,50 @@
...
+    private final List<? extends AbstractNotificationProvider> notificationProviders;
     private final NotificationTemplateRepository templateRepository;
-    @Autowired
-    private final InetAddressProvider inetAddressProvider;
-
     @Autowired
     @Qualifier("singleThreadedExecutor")
     private ExecutorService executor;
 
+    private final Environment environment;
```
Comment (VadymMakitra) [inline service/src/main/java/greencity/service/notification/NotificationServiceImpl.java]: Instead of using the Environment class Please add your properties here: https://github.com/ita-social-projects/GreenCityUBS/blob/dev/core/src/main/java/greencity/configuration/RedirectionConfigProp.java
Or create a new one if needed by following the example.

**Review by RomaMocherniuk — APPROVED** [review]
