### PR TITLE
Modified security configuration for PATCH ubs/update-address endpoint

### LINKED ISSUE #8670: [UBS Orders][API] PATCH /ubs/update-address returns 403 Forbidden for valid user with correct data
**Reproducible:** always
**Build found:** 22.06.2025

**Preconditions**

1. User is on https://greencity-ubs.greencity.cx.ua/swagger-ui/index.html#/address-controller/updateAddress
2. The user is authorized as a customer.
3. The user has access to orderId = 236, and the address id = 109

**Steps to reproduce**
1. Send the following PATCH request to the endpoint: 
 {
    "orderAddressExportDetails": {
        "id": 109,
        "districtUk": "Шевченківський район",
        "districtEn": "Shevchenkivskyi District",
        "streetUk": "вулиця Марка Безручка",
        "streetEn": "Marka Bezruchka Street",
        "houseCorpus": "6",
        "entranceNumber": "1",
        "houseNumber": "23",
        "cityUk": "Київ",
        "cityEn": "Kyiv",
        "regionUk": "місто Київ",
        "regionEn": "Kyiv",
        "addressComment": "null"
    },
    "orderId": 236
}
2. Observe the response status and message.

**Actual result**

1. Response status: 403 Forbidden

Image

**Expected result**

1. The address for the specified order is successfully updated.
2. Response status: 200 OK

**Additional Notes:**

1. When the same request is executed under an admin role, the server returns 200 OK, but the changes are not reflected in the database

### PR DESCRIPTION
**Pull request by markotymofeiuk**
# GreenCityUBS PR
[#8670](https://github.com/ita-social-projects/GreenCity/issues/8670)

## Summary Of Changes :fire:
Modified SecurityConfig for /ubs/update-address, refactored the endpoint

## Changed
* Modified SecurityConfig so that PATCH `/ubs/update-address` endpoint is only accessible to role `UBS_EMPLOYEE` to match existing event logging logic of `AddressService` and prevent ambiguous behavior.
* Refactored /ubs/update-address endpoint, which now returns `OrderAddressDtoResponse` with 200 status code, provided relevant documentation for Swagger.

## Summary by CodeRabbit

* **New Features**
  * The update address endpoint now returns updated address information in the response, allowing users to receive confirmation and details of their updated address.

* **Bug Fixes**
  * Improved API documentation to accurately reflect the response content for the update address endpoint.

* **Refactor**
  * Adjusted access control for the update address endpoint to allow only specific user roles to perform updates.

### CODE REVIEW

File: core/src/main/java/greencity/controller/AddressController.java [hunk 1]
```diff
@@ -206,22 +208,22 @@ public ResponseEntity<List<DistrictDto>> getAllDistrictsForKyiv() {
...
         @ApiResponse(responseCode = "401", description = HttpStatuses.UNAUTHORIZED, content = @Content),
         @ApiResponse(responseCode = "403", description = HttpStatuses.FORBIDDEN, content = @Content),
         @ApiResponse(responseCode = "404", description = HttpStatuses.NOT_FOUND, content = @Content)
     })
     @PatchMapping("/update-address")
-    public ResponseEntity<Void> updateAddress(@RequestBody @Valid UpdateAddressDto addressDto,
-        @Parameter(hidden = true) Principal principal) {
-        addressService.addressUpdate(addressDto, principal.getName());
-        return ResponseEntity.ok().build();
+    public ResponseEntity<Optional<OrderAddressDtoResponse>> updateAddress(
```
Comment (olehio-p) [inline core/src/main/java/greencity/controller/AddressController.java]: Returning `ResponseEntity<Optional<T>>` directly is generally not the best practice. And can we really get empty optional here? Optional returns only from this method `public Optional<OrderAddressDtoResponse> updateAddress(OrderAddressExportDetailsDtoUpdate dtoUpdate, Order order, String email)` in methods call chain in `AddressServiceImpl`. There it looks redundant to return optional like this one `return Optional.of(modelMapper.map(updatedOrderAddress, OrderAddressDtoResponse.class));` because it's not really the case to wrap it into Optional and we don't have any other example of doing so in our codebase.

**Review by olehio-p — CHANGES_REQUESTED** [review]

**Review by olehio-p — APPROVED** [review]

**Review by dimasowner — APPROVED** [review]

**Review by RostyslavZadyraichuk — APPROVED** [review]
